export const config={
  host:process.env.AGENT_HOST??"127.0.0.1",
  port:Number(process.env.PORT??8787),
  allowedOrigins:(process.env.AGENT_ALLOWED_ORIGINS??"https://www.figma.com,https://figma.com,http://localhost:8787,http://127.0.0.1:8787").split(",").map(v=>v.trim()).filter(Boolean),
  apiKey:process.env.OPENROUTER_API_KEY??process.env.LLM_API_KEY??"",
  baseUrl:(process.env.LLM_BASE_URL??"https://openrouter.ai/api/v1").replace(/\/$/,""),
  model:process.env.LLM_MODEL??"qwen/qwen3.8-27b:free",
  fallbackModels:(process.env.LLM_FALLBACK_MODELS??"openrouter/free,dots-studio/dots3-note-preview:free").split(",").map(v=>v.trim()).filter(Boolean),
  temperature:Number(process.env.LLM_TEMPERATURE??0.1),
  maxTokens:Number(process.env.LLM_MAX_TOKENS??6000),
  retries:Number(process.env.LLM_RETRIES??1),
  retryBaseMs:Number(process.env.LLM_RETRY_BASE_MS??1200),
  maxActions:Number(process.env.MAX_ACTIONS_PER_PLAN??80),
  maxRepairLoops:Number(process.env.MAX_REPAIR_LOOPS??2),
  supabaseUrl:(process.env.SUPABASE_URL??"").replace(/\/$/,""),
  supabaseServiceRoleKey:process.env.SUPABASE_SERVICE_ROLE_KEY??"",
  projectKey:process.env.UX_MEMORY_PROJECT_KEY??"default",
  memoryVisualReferences:(process.env.UX_MEMORY_VISUAL_REFERENCES??"false").toLowerCase()==="true"
};
